"""Calibration against ToolRet's published leaderboard.

Our six-baseline ladder is ours, run on ToolRet with our own metrics. That is defensible
— their task is *rank tools for a query*, ours is *choose a subset under a token budget* —
but it leaves us with no external reference point. A poor ``semantic-retrieval`` score
would then be uninterpretable: we could not tell a real finding from a weak
implementation of our own retrieval.

So: run a published retriever over the same data, score it with the *standard* retrieval
metrics (nDCG@10, recall@k), and check we reproduce that model's reported number. This
sanity-checks the whole pipeline — loader, catalog identity, gold-label extraction,
embedding wiring — not just baseline 4. A silent bug anywhere upstream shows up here as a
number that is obviously wrong, rather than as a gate decision that is quietly wrong.

**Match the setting, or the check inverts.** The leaderboard publishes with- and
without-instruction tabs; the frontier scores query-only. Comparing a query-only run to
with-instruction numbers reports a correct run as broken, which is exactly what happened
before 2026-08-07. ``--no-instruction`` selects the band as well as the query text.

    uv run --extra bench python -m mcp_gateway_router.calibrate --model e5-base
    uv run --extra bench python -m mcp_gateway_router.calibrate --model bm25 --no-instruction
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

from .baselines import BM25Scorer, RelevanceScorer
from .catalog import Catalog
from .data import load_catalog, load_examples, restrict_to_catalog
from .embedding import CALIBRATION_MODELS
from .frontier import Example

# BM25 needs no download and no GPU, and it is the published band's floor — so it is both
# the cheapest calibration point and the most diagnostic. Ordering is what we actually
# check: sparse < general dense < tool-tuned dense. Absolute nDCG is protocol-sensitive;
# the ordering is robust to protocol, which is why one number was never enough.
SCORERS = ["bm25", *CALIBRATION_MODELS]


# ToolRet leaderboard, category **Web API**, both settings (HuggingFace, read 2026-08-07;
# source `data/w-w-API.xlsx` and `data/w-wo-API.xlsx` in the leaderboard Space).
# NDCG@10 / Recall@10, as percentages.
#
# The leaderboard's own config.yaml defines exactly two settings:
#
#     settings:         ["w/ meta w/ inst", "w/ meta w/o inst"]
#     settings_mapping: {"w/ meta w/ inst": "w-w", "w/ meta w/o inst": "w-wo"}
#     types:            [Avg, Code, API, Customized]   # Avg→All, API→Web API
#
# So *meta is held constant* — tool metadata is in the document in every published number,
# and there is no "w/o meta" tab. The only axis is `inst`: whether ToolRet's per-query
# instruction is prepended. Those instructions are generated by GPT-4o under an explicitly
# "target-aware" strategy, which is why they leak target vocabulary (measured: 20.3% of the
# gold tool's description terms, against 7.4% for the bare query).
#
# ⚠️ Corrected 2026-08-07. This table previously held the "All" / w-inst tab, which was
# wrong on both axes: "All" averages Code Function + Web API + Customized App while we run
# `apibank` (a Web API subset), and the frontier scores query-only while the band was
# with-instruction. Every query-only run was therefore judged against with-instruction
# numbers and reported as "BELOW the band" — a false alarm sending the reader to debug a
# non-bug. Select the band by setting, and compare to the *same model* wherever possible.
PUBLISHED_API_WITH_INST = {
    "jinaai/jina-reranker-v2-base-multilingual": (41.34, 49.67),
    "BAAI/bge-reranker-v2-m3": (35.20, 44.46),
    "BAAI/bge-reranker-v2-gemma": (33.86, 42.06),
    "bzantium/NV-Embed-v1": (30.60, 38.80),
    "BAAI/bge-large-en-v1.5": (30.29, 39.14),
    "intfloat/e5-mistral-7b-instruct": (29.95, 39.18),
    "Alibaba-NLP/gte-base-en-v1.5": (29.06, 37.09),
    "bm25": (28.74, 36.63),
    "intfloat/e5-small-v2": (26.54, 33.67),
    "BAAI/bge-base-en-v1.5": (26.48, 35.28),
    "intfloat/e5-base-v2": (24.59, 32.90),
    "Alibaba-NLP/gte-large-en-v1.5": (24.51, 31.61),
    "sentence-transformers/gtr-t5-large": (24.40, 30.66),
    "intfloat/e5-large-v2": (23.51, 31.50),
    "facebook/contriever-msmarco": (23.04, 28.82),
    "castorini/monot5-base-msmarco": (22.69, 29.39),
    "sentence-transformers/gtr-t5-base": (20.85, 27.54),
    "mixedbread-ai/mxbai-rerank-large-v1": (17.81, 26.02),
    "colbert": (16.18, 20.05),
    "sentence-transformers/all-MiniLM-L6-v2": (12.71, 18.88),
}
PUBLISHED_API_NO_INST = {
    "BAAI/bge-reranker-v2-gemma": (36.68, 45.37),
    "jinaai/jina-reranker-v2-base-multilingual": (33.85, 42.75),
    "BAAI/bge-reranker-v2-m3": (32.47, 40.87),
    "bzantium/NV-Embed-v1": (30.43, 37.36),
    "castorini/monot5-base-msmarco": (27.63, 34.40),
    "intfloat/e5-mistral-7b-instruct": (25.81, 33.34),
    "mixedbread-ai/mxbai-rerank-large-v1": (23.64, 30.44),
    "BAAI/bge-large-en-v1.5": (22.59, 30.25),
    "Alibaba-NLP/gte-large-en-v1.5": (22.21, 29.08),
    "BAAI/bge-base-en-v1.5": (22.13, 29.55),
    "Alibaba-NLP/gte-base-en-v1.5": (21.58, 29.16),
    "colbert": (21.55, 26.37),
    "sentence-transformers/gtr-t5-large": (21.28, 27.57),
    "bm25": (20.20, 25.83),
    "facebook/contriever-msmarco": (20.20, 25.56),
    "intfloat/e5-base-v2": (20.06, 26.15),
    "intfloat/e5-small-v2": (19.24, 25.00),
    "intfloat/e5-large-v2": (18.42, 24.97),
    "sentence-transformers/gtr-t5-base": (16.75, 22.95),
    "sentence-transformers/all-MiniLM-L6-v2": (11.04, 15.58),
}

# A min/max band over 20 models spans 12.7–41.3, which would call almost anything "within
# band" — a check that cannot fail is not a check. So when we run a model that is itself on
# the leaderboard, compare like for like against *that model's* number. The band is only the
# fallback for the ToolRet-fine-tuned checkpoints, which have no published row.
#
# ±5 nDCG points is deliberately loose: our corpus is `web` (37k) rather than their full API
# corpus, and `apibank` is one subset of Web API rather than all of it. A model reproducing
# inside that tolerance validates the loader, the gold labels, the metric and the wiring.
MATCH_TOLERANCE = 5.0

# The ToolRet-tuned checkpoints have no published row, but each was fine-tuned *from* a
# model that does — so the base model's number is a floor the tuned one must clear by more
# than measurement noise. This is what keeps the check loud for our default model: the
# missing-instruction bug produced 25.52 against a base of 24.59, a +0.9 "gain" from
# fine-tuning on 200k in-domain examples, which is not a plausible result. Comparing to a
# 20-model spread would have shrugged at it; comparing to its own base does not.
TUNED_BASE = {
    "mangopy/ToolRet-trained-e5-base-v2": "intfloat/e5-base-v2",
    "mangopy/ToolRet-trained-e5-large-v2": "intfloat/e5-large-v2",
    "mangopy/ToolRet-trained-bge-large-en-v1.5": "BAAI/bge-large-en-v1.5",
}


def published_table(use_instruction: bool) -> dict[str, tuple[float, float]]:
    return PUBLISHED_API_WITH_INST if use_instruction else PUBLISHED_API_NO_INST


def verdict(ndcg_pct: float, model_id: str, use_instruction: bool) -> str:
    """Is our number plausibly the same measurement as the published one?"""
    table = published_table(use_instruction)
    setting = "w/ meta w/ inst" if use_instruction else "w/ meta w/o inst"
    scores = sorted((v[0] for v in table.values()), reverse=True)
    low, high = scores[-1], scores[0]

    if model_id in table:
        published = table[model_id][0]
        delta = ndcg_pct - published
        if abs(delta) <= MATCH_TOLERANCE:
            return (
                f"REPRODUCES {model_id} on the '{setting}' / Web API tab: published "
                f"{published:.2f}, ours {ndcg_pct:.2f} ({delta:+.2f}). Within the ±"
                f"{MATCH_TOLERANCE:.0f} tolerance — loader, gold labels, metric and wiring "
                "all check out."
            )
        return (
            f"DOES NOT REPRODUCE {model_id} on the '{setting}' / Web API tab: published "
            f"{published:.2f}, ours {ndcg_pct:.2f} ({delta:+.2f}), outside the ±"
            f"{MATCH_TOLERANCE:.0f} tolerance. This is a like-for-like comparison — same "
            "model, same setting, same category — so corpus size and subset choice are the "
            "only benign explanations, and neither should move it this far. Check the "
            "document text we index against what the leaderboard indexes ('w/ meta' means "
            "the full tool documentation), and the tokenizer."
        )

    rank = sum(1 for s in scores if s > ndcg_pct) + 1
    position = (
        f"On the '{setting}' / Web API tab it ranks {rank} of {len(scores) + 1}, against a "
        f"published spread of {low:.2f}–{high:.2f}."
    )

    base = TUNED_BASE.get(model_id)
    if base and base in table:
        base_score = table[base][0]
        gain = ndcg_pct - base_score
        if gain <= MATCH_TOLERANCE:
            return (
                f"SUSPECT: {model_id} scored {ndcg_pct:.2f} against its own base {base} at "
                f"{base_score:.2f} — a gain of only {gain:+.2f} from fine-tuning on 200k "
                f"in-domain examples, which is not a plausible result. {position} Check the "
                "setting first: is the instruction being applied when it should be?"
            )
        return (
            f"{model_id} beats its base {base} by {gain:+.2f} ({base_score:.2f} → "
            f"{ndcg_pct:.2f}) on the '{setting}' / Web API tab — the expected shape for a "
            f"tuned checkpoint. {position} Note it means the retriever saw this benchmark's "
            "training split, which flatters baseline 4 — the conservative direction for "
            "Gate 0."
        )

    return (
        f"no published row for {model_id} and no known base model to compare against. "
        f"{position}"
    )


def build_scorer(name: str, catalog: Catalog) -> RelevanceScorer:
    if name == "bm25":
        return BM25Scorer(catalog)
    from .embedding import EmbeddingScorer

    return EmbeddingScorer(catalog, model_name=CALIBRATION_MODELS[name])


def rank_of_required(
    scorer: RelevanceScorer,
    example: Example,
    catalog: Catalog,
    depth: int,
    use_instruction: bool = True,
) -> list[int]:
    """1-based ranks of each required tool in the retrieved list. ``depth+1`` if unranked."""
    # retrieval_text, not task: the published leaderboard's "w/ inst" setting prepends
    # ToolRet's per-query instruction. Comparing our query-only score against their
    # w/-inst numbers is what put us below BM25.
    query = example.retrieval_text if use_instruction else example.task
    scored = sorted(catalog, key=lambda t: (-scorer.score(query, t), t.name))
    positions = {t.key: i + 1 for i, t in enumerate(scored[:depth])}
    return [positions.get(key, depth + 1) for key in example.required]


def ndcg_at_k(ranks: list[int], n_relevant: int, k: int) -> float:
    dcg = sum(1.0 / math.log2(r + 1) for r in ranks if r <= k)
    ideal = sum(1.0 / math.log2(i + 2) for i in range(min(n_relevant, k)))
    return dcg / ideal if ideal else 0.0


def evaluate_retriever(
    scorer: RelevanceScorer,
    examples: list[Example],
    catalog: Catalog,
    k: int = 10,
    use_instruction: bool = True,
) -> dict:
    depth = max(k, 100)
    ndcg_sum = recall_sum = hit1 = 0.0

    for example in examples:
        ranks = rank_of_required(scorer, example, catalog, depth, use_instruction)
        ndcg_sum += ndcg_at_k(ranks, len(example.required), k)
        recall_sum += sum(1 for r in ranks if r <= k) / len(ranks)
        if min(ranks) == 1:
            hit1 += 1

    n = max(len(examples), 1)
    return {
        f"ndcg@{k}": round(ndcg_sum / n, 4),
        f"recall@{k}": round(recall_sum / n, 4),
        "hit@1": round(hit1 / n, 4),
        "n_examples": len(examples),
        "catalog_size": len(catalog),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Calibrate against a published retriever.")
    parser.add_argument("--model", default="toolret-e5-base", choices=SCORERS)
    parser.add_argument("--tools-subset", default="web")
    parser.add_argument("--queries-subset", default="apibank")
    parser.add_argument("--tool-limit", type=int, default=None)
    parser.add_argument("--query-limit", type=int, default=200)
    parser.add_argument("-k", type=int, default=10)
    parser.add_argument(
        "--no-instruction",
        action="store_true",
        help="score query-only, matching the leaderboard's w/o-inst tab",
    )
    parser.add_argument("--out", type=Path, default=Path("results/calibration.json"))
    args = parser.parse_args(argv)

    catalog = load_catalog(args.tools_subset, limit=args.tool_limit)
    examples = restrict_to_catalog(
        load_examples(args.queries_subset, limit=args.query_limit), catalog
    )
    scorer = build_scorer(args.model, catalog)
    metrics = evaluate_retriever(
        scorer, examples, catalog, k=args.k, use_instruction=not args.no_instruction
    )
    metrics["setting"] = "w/o inst" if args.no_instruction else "w/ inst"
    metrics["model"] = CALIBRATION_MODELS.get(args.model, args.model)

    import json

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(metrics, indent=2))
    for key, value in metrics.items():
        print(f"{key:>14}: {value}")
    ndcg_pct = metrics[f"ndcg@{args.k}"] * 100
    print(
        f"\nnDCG@{args.k} = {ndcg_pct:.2f}% — "
        f"{verdict(ndcg_pct, metrics['model'], not args.no_instruction)}"
    )
    print(
        "Reference is the ToolRet leaderboard, category Web API, setting matched to "
        "--no-instruction. `apibank` is a Web API subset, so the 'All' tab is never the "
        "right comparison."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
